# 加解密根密码
jasypt:
  encryptor:
    password: jun #根密码

# redis 相关
spring:
  redis:
    password:
    host: cloud-redis
    port: 6379

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    # 自动刷新Mapper对应的XML文件
    refresh: true
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

## spring security 配置
security:
  oauth2:
    client:
      # 默认放行url,如果子模块重写这里的配置就会被覆盖
      ignore-urls:
        - '/actuator/**'
        - '/v2/api-docs'
    resource:
      loadBalanced: true
      token-info-uri: http://cloud-auth/oauth/check_token