## spring security 配置
security:
  oauth2:
    client:
      #client-id: ENC(IFj1XPtcQhZ4SgoO8mVPJw==) #cloud
      #client-secret: ENC(IFj1XPtcQhZ4SgoO8mVPJw==) #cloud
      client-id: ENC(PcClddn/IjlbNecQ1aYwpA==) #cloud2
      client-secret: ENC(PcClddn/IjlbNecQ1aYwpA==) #cloud2
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - '/actuator/**'
        - '/v2/api-docs'
        - '/user/info/*'

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://cloud-mysql:3307/cloud_project?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

# Logger Config
logging:
  level:
    com.github.jun.cloud.upms.mapper: debug

