# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://cloud-mysql:3307/cloud_project?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

